In [3]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [4]:
iris_data = datasets.load_iris()

In [5]:
classifier = KNeighborsClassifier()

In [6]:
X = scale(iris_data.data)

In [7]:
y = pd.DataFrame(iris_data.target)

In [8]:
classifier.fit(X,y)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3 ,random_state = 10)

In [10]:
y_predict = classifier.predict(X_test)

In [11]:
y_predict

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [12]:
y_test

0
87   1
111  2
10   0
91   1
49   0
60   1
72   1
67   1
39   0
55   1
66   1
142  2
53   1
1    0
19   0
112  2
85   1
38   0
21   0
35   0
102  2
132  2
126  2
24   0
61   1
2    0
95   1
90   1
76   1
117  2
58   1
97   1
129  2
114  2
146  2
47   0
124  2
120  2
118  2
141  2
26   0
43   0
59   1
41   0
56   1

In [13]:
print(classification_report(y_test,y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.94      0.97        17
          2       0.93      1.00      0.97        14

avg / total       0.98      0.98      0.98        45



In [14]:
confusion_matrix(y_test,y_predict)

array([[14,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 14]], dtype=int64)

In [15]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score,accuracy_score,confusion_matrix,classification_report
from sklearn import datasets
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


In [16]:
model = KNeighborsClassifier()


In [17]:
iris = datasets.load_iris()

In [18]:
X = scale(iris.data)
y = pd.DataFrame(iris.target)

In [19]:
model.fit(X,y)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.3, random_state = 10)

In [21]:
y_predict = model.predict(X_test)

In [22]:
y_predict

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [23]:
print(classification_report(y_test,y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.94      0.97        17
          2       0.93      1.00      0.97        14

avg / total       0.98      0.98      0.98        45



In [24]:
r2_score(y_test,y_predict)

0.9642857142857143

In [25]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
from sklearn import preprocessing
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import matplotlib.pyplot as plt

In [26]:
model = KNeighborsClassifier()

In [27]:
df = pd.read_csv("mtcars.csv")

In [28]:
df.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [29]:
X = df.loc[:,['mpg','hp','wt']]

In [30]:
y = df.loc[:,['am']]

In [31]:
X = preprocessing.scale(X)
model.fit(X,y)


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 1)

In [33]:
y_predict = model.predict(X_test)

In [34]:
y_predict

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [35]:
y_test

am
27   1
3    0
22   0
18   1
23   0
17   1
21   0
28   1
19   1
14   0

In [36]:
print(classification_report(y_test,y_predict))

             precision    recall  f1-score   support

          0       0.83      1.00      0.91         5
          1       1.00      0.80      0.89         5

avg / total       0.92      0.90      0.90        10



In [37]:
r2_score(y_predict,y_test)

0.5833333333333334

In [38]:
print(confusion_matrix(y_test,y_predict))

[[5 0]
 [1 4]]


In [39]:
#KNN usin bank data

In [68]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale,LabelEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score

In [42]:
df = pd.read_csv("bank-full.csv",";")

In [43]:

df.head(4)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no

In [46]:
#Encodig job column 
enc = LabelEncoder()
enc.fit(df.job)
df.job = enc.transform(df.job)
df.head()

age  job  marital  education default  balance housing loan  contact  day  \
0   58    4  married   tertiary      no     2143     yes   no  unknown    5   
1   44    9   single  secondary      no       29     yes   no  unknown    5   
2   33    2  married  secondary      no        2     yes  yes  unknown    5   
3   47    1  married    unknown      no     1506     yes   no  unknown    5   
4   33   11   single    unknown      no        1      no   no  unknown    5   

  month  duration  campaign  pdays  previous poutcome   y  
0   may       261         1     -1         0  unknown  no  
1   may       151         1     -1         0  unknown  no  
2   may        76         1     -1         0  unknown  no  
3   may        92         1     -1         0  unknown  no  
4   may       198         1     -1         0  unknown  no

In [47]:
enc = LabelEncoder()
enc.fit(df.default)
df.default = enc.transform(df.default)
df.head()

age  job  marital  education  default  balance housing loan  contact  day  \
0   58    4  married   tertiary        0     2143     yes   no  unknown    5   
1   44    9   single  secondary        0       29     yes   no  unknown    5   
2   33    2  married  secondary        0        2     yes  yes  unknown    5   
3   47    1  married    unknown        0     1506     yes   no  unknown    5   
4   33   11   single    unknown        0        1      no   no  unknown    5   

  month  duration  campaign  pdays  previous poutcome   y  
0   may       261         1     -1         0  unknown  no  
1   may       151         1     -1         0  unknown  no  
2   may        76         1     -1         0  unknown  no  
3   may        92         1     -1         0  unknown  no  
4   may       198         1     -1         0  unknown  no

In [49]:
enc .fit(df.housing)
df.housing = enc.transform(df.housing)
df.head()

age  job  marital  education  default  balance  housing loan  contact  day  \
0   58    4  married   tertiary        0     2143        1   no  unknown    5   
1   44    9   single  secondary        0       29        1   no  unknown    5   
2   33    2  married  secondary        0        2        1  yes  unknown    5   
3   47    1  married    unknown        0     1506        1   no  unknown    5   
4   33   11   single    unknown        0        1        0   no  unknown    5   

  month  duration  campaign  pdays  previous poutcome   y  
0   may       261         1     -1         0  unknown  no  
1   may       151         1     -1         0  unknown  no  
2   may        76         1     -1         0  unknown  no  
3   may        92         1     -1         0  unknown  no  
4   may       198         1     -1         0  unknown  no

In [54]:
enc.fit(df.loan)
df.loan = enc.transform(df.loan)
enc.fit(df.marital)
df.marital = enc.transform(df.marital)

In [55]:
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   58    4        1   tertiary        0     2143        1     0  unknown   
1   44    9        2  secondary        0       29        1     0  unknown   
2   33    2        1  secondary        0        2        1     1  unknown   
3   47    1        1    unknown        0     1506        1     0  unknown   
4   33   11        2    unknown        0        1        0     0  unknown   

   day month  duration  campaign  pdays  previous poutcome   y  
0    5   may       261         1     -1         0  unknown  no  
1    5   may       151         1     -1         0  unknown  no  
2    5   may        76         1     -1         0  unknown  no  
3    5   may        92         1     -1         0  unknown  no  
4    5   may       198         1     -1         0  unknown  no

In [56]:
X = df.loc[:,['job','marital','default','balance','loan','housing']]
y = df.y

In [60]:
model = KNeighborsClassifier()
model.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state = 10)


In [62]:
y_predict = model.predict(X_test)

In [63]:
y_predict

array(['no', 'no', 'no', ..., 'no', 'yes', 'no'], dtype=object)

In [65]:
y_test.ravel()

array(['no', 'no', 'no', ..., 'no', 'yes', 'no'], dtype=object)

In [70]:
print(classification_report(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))


             precision    recall  f1-score   support

         no       0.91      0.98      0.94     12006
        yes       0.65      0.24      0.35      1558

avg / total       0.88      0.90      0.88     13564

[[11802   204]
 [ 1186   372]]
