In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd


In [2]:
X = [[1000],[1200],[1500]]
price=[50,70,80]



In [3]:
model = LinearRegression()

In [4]:
model.fit(X,price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
model.predict([[2000]])

array([111.05263158])

In [6]:
df = pd.read_csv("G:\mtcars.csv")

In [7]:
df.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X= df.loc[:,['hp','wt','am']]
y = df.mpg

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state = 1)

In [10]:
X_train.shape

(22, 3)

In [11]:
X_test.shape

(10, 3)

In [12]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
y_predict = model.predict(X_test)

In [14]:
y_predict

array([24.97230248, 20.40618863, 18.72350798, 26.55141456, 14.99221496,
       24.81645629, 18.53175266, 16.7556445 , 25.66953552, 12.99770533])

In [15]:
y_test

27    30.4
3     21.4
22    15.2
18    30.4
23    13.3
17    32.4
21    15.5
28    15.8
19    33.9
14    10.4
Name: mpg, dtype: float64

In [16]:
from sklearn.metrics import r2_score

In [17]:
r2_score(y_test,y_predict)

0.7217461793195252

In [18]:
hp = pd.read_csv("G:/hp_data.csv")


In [19]:
hp.head()

Unnamed: 0     price       place                 built  sqft    sale  \
0        1341   6300000  BTM Layout  Super built-up  Area  1450  Resale   
1        2126  11500000   Yelahanka  Super built-up  Area  2190  Resale   
2         816   3800000  Whitefield  Super built-up  Area  1019  Resale   
3        2708  10500000  Ambalipura  Super built-up  Area  1857  Resale   
4        1041  11500000   Yelahanka  Super built-up  Area  2190  Resale   

   yearsOld  floor  totalFloor  bhk  
0         5      1           4    1  
1         5      3           5    3  
2         1      2           5    2  
3        15      4           5    4  
4         5      3           5    3

In [20]:
model = LinearRegression()

In [78]:
X = hp.loc[:,['floor','bhk','sqft','yearsOld','place','totalFloor']]

In [79]:
y = hp.price

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state = 12)

In [81]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [82]:
y_predict = model.predict(X_test)

In [83]:
y_predict

array([13385219.13040805,  3846121.34030319, 12756384.09830364, ...,
        1499702.75634208,  7708035.55831329,  9581945.00720289])

In [84]:
y_test.head()

1486    15000000
357      3800000
2146    11500000
2195     7350000
654     10500000
Name: price, dtype: int64

In [85]:
from sklearn.metrics import r2_score
#to find score

In [86]:
r2_score(y_test,y_predict)

0.8548185953885742

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
enc = LabelEncoder()

In [48]:
encoded = enc.fit(hp.place)

In [49]:
encode_place = enc.transform(hp.place)

In [50]:
enc.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

In [51]:
hp.place = enc.transform(hp.place)

In [52]:
hp.head()

Unnamed: 0     price  place                 built  sqft    sale  yearsOld  \
0        1341   6300000      2  Super built-up  Area  1450  Resale         5   
1        2126  11500000     14  Super built-up  Area  2190  Resale         5   
2         816   3800000     12  Super built-up  Area  1019  Resale         1   
3        2708  10500000      1  Super built-up  Area  1857  Resale        15   
4        1041  11500000     14  Super built-up  Area  2190  Resale         5   

   floor  totalFloor  bhk  
0      1           4    1  
1      3           5    3  
2      2           5    2  
3      4           5    4  
4      3           5    3

In [87]:
s =pd.Series(list(hp.place))

In [89]:
pd.get_dummies(s).head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
2   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
3   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1

In [90]:
#Logistic Regression

In [91]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split

In [92]:
pass_data = pd.read_csv("pass.csv")

In [93]:
pass_data.head()

Hours  Pass
0   0.50     0
1   0.75     0
2   1.00     0
3   1.25     0
4   1.50     0

In [94]:
X = pass_data.Hours
y = pass_data.Pass
X = X.values.reshape(-1,1)

In [96]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 10)

In [97]:
model = LogisticRegression()

In [98]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [99]:
y_predict = model.predict(X_test)

In [100]:
y_predict

array([1, 1, 0, 0, 0, 1], dtype=int64)

In [101]:
accuracy_score(y_predict,y_test)

0.6666666666666666

In [102]:
confusion_matrix(y_predict,y_test)

array([[3, 0],
       [2, 1]], dtype=int64)

In [109]:
def student_result(hours):
    if(model.predict(hours) == 1): # here one is True.
        return "PASS"
    else:
        return "FAIL"

In [117]:
student_result()

'PASS'

In [119]:
 #For cardata#
df = pd.read_csv("G:/mtcars.csv")

In [120]:
df.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [122]:
from sklearn.preprocessing import scale

In [123]:
X = df.mpg

In [124]:
X = scale(X)

In [126]:
model = LogisticRegression()

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
pass_data = pd.read_csv("pass.csv")

In [3]:
pass_data.head()

Hours  Pass
0   0.50     0
1   0.75     0
2   1.00     0
3   1.25     0
4   1.50     0

In [11]:
X = pass_data.Hours
Y = pass_data.Pass
X =X.values.reshape(-1,1)

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1)

In [13]:
model = LogisticRegression()

In [14]:
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
Y_predict = model.predict(X_test)

In [16]:
Y_predict

array([1, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [17]:
accuracy_score(Y_predict,Y_test)

1.0

In [18]:
confusion_matrix(Y_predict,Y_test)

array([[4, 0],
       [0, 5]], dtype=int64)